refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {l} {M} {m}{n}"

  easymund:
    kind: file
    path: "log/easymund.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {l} {m}{n}"

root:
  level: debug
  appenders:
    - stdout

loggers:
  easymund_server:
    level: debug
    appenders:
      - stdout
      - easymund
    additive: false
